// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATMsrWlzbMImTEmmvI39nB8QCNcNhgbRo',
    appId: '1:28041757619:web:6c3be0cee970258c7141c6',
    messagingSenderId: '28041757619',
    projectId: 'chack-ace76',
    authDomain: 'chack-ace76.firebaseapp.com',
    storageBucket: 'chack-ace76.appspot.com',
    measurementId: 'G-P0PMS4TLQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE0j2H5_42ubgFuc_mpWYEjNJ6sLLp8_E',
    appId: '1:28041757619:android:6d6da4cdad44ce1b7141c6',
    messagingSenderId: '28041757619',
    projectId: 'chack-ace76',
    storageBucket: 'chack-ace76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCbmH98jNlAWXWYpZoFDn2-FDuEbvsqqc',
    appId: '1:28041757619:ios:0c78749dab444f097141c6',
    messagingSenderId: '28041757619',
    projectId: 'chack-ace76',
    storageBucket: 'chack-ace76.appspot.com',
    iosClientId: '28041757619-72s45am9tdj4j4lndl85ke69c6j40irc.apps.googleusercontent.com',
    iosBundleId: 'com.example.chackProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCbmH98jNlAWXWYpZoFDn2-FDuEbvsqqc',
    appId: '1:28041757619:ios:0c78749dab444f097141c6',
    messagingSenderId: '28041757619',
    projectId: 'chack-ace76',
    storageBucket: 'chack-ace76.appspot.com',
    iosClientId: '28041757619-72s45am9tdj4j4lndl85ke69c6j40irc.apps.googleusercontent.com',
    iosBundleId: 'com.example.chackProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATMsrWlzbMImTEmmvI39nB8QCNcNhgbRo',
    appId: '1:28041757619:web:7bfa2f3d0e2073687141c6',
    messagingSenderId: '28041757619',
    projectId: 'chack-ace76',
    authDomain: 'chack-ace76.firebaseapp.com',
    storageBucket: 'chack-ace76.appspot.com',
    measurementId: 'G-CLRRZN5T7Y',
  );
}
